---
- name: task level varaibles
  hosts: local
  connection: local
  vars:
    COURSE: Devops with aws
    DURATION: 10HR
    TRAINER: null
  tasks:
    - name: Print course information
      vars:
        COURSE: Ansible
      ansible.builtin.debug:
        msg: Hello {{ COURSE }},Course Duration {{ DURATION }},Trainer is {{ TRAINER }}

