---
- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh, Suresh, Raheem, Joseph"
  tasks:
  - name: check undefined varaible
    ansible.builtin.debug:
      msg: "hello {{ person | default('ramesh')}}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert to uppercase
    vars:
     name: "satyam naidu k"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lowercase
    vars:
     name: "SAtyam naidu K"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"


